---
application:
  name: "kiyanpay-final"
  project: "Landing"
  organization: "KiyanPay"
  port: 3000
routers:
- name: "main-kiyanpay-final"
  routes:
  - application_name: "kiyanpay-final"
    paths:
    - "/*"
