meta_product_name: "KiyanPay"
meta_title: "KiyanPay - Banking For All"
meta_description: "Putting your money where our mouth is!  Open a bank account in under five minutes today. No fees, no fuss just finance. "
meta_image: "Metaimage.png" # should exist in `app/assets/images/`
twitter_account: "@KiyanPay"   # required for Twitter Cards
