Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'blog', to: 'pages#blog'
  get 'professional', to: 'pages#professional'
  get 'terms' , to: 'pages#terms'
  get 'privacy' , to: 'pages#privacy'
  get 'cookies', to: 'pages#cookies'
  get 'contact', to: 'pages#contact'
  get 'stress', to: 'pages#stress'
  get 'careers', to: 'pages#careers'
  get "three-things-we-should-have-been-taught-at-school" , to: 'pages#three-things-we-should-have-been-taught-at-school'
  get "accounting-software-for-small-businesses" , to: 'pages#accounting-software-for-small-businesses'
  get "financial-security" , to: 'pages#financial-security'
  get "making-money-while-sleeping" , to: 'pages#making-money-while-sleeping'
  get "staying-safe-online" , to: 'pages#staying-safe-online'
  get "five-money-supersitions" , to: 'pages#five-money-supersitions'
  get "dream-house-dream-price" , to: 'pages#dream-house-dream-price'
  get "money-muling" , to: 'pages#money-muling'
  get "small-business-grants" , to: 'pages#small-business-grants'
  get "intellectual-property-law" , to: 'pages#intellectual-property-law'
  get "currencies", to: 'pages#currencies'
  get "philosophy" , to: 'pages#philosophy'
  get "multi-currency-cards", to: 'pages#multi-currency-cards'
  get "no-more-borders", to: 'pages#no-more-borders'
  get "social-banking" , to: 'pages#social-banking'
  get "direct-debit" , to: 'pages#direct-debit'
  get "fraud-protection" , to: 'pages#fraud-protection'
  get "transferring-an-overseas-pension", to: 'pages#transferring-an-overseas-pension'
  get "how-to-sell-your-business" , to: 'pages#how-to-sell-your-business'
  get "is-this-website-real" , to: 'pages#is-this-website-real'
  get "scam-calls", to: 'pages#scam-calls'
  get "scam-messages", to: 'pages#scam-messages'
  get "password-protection" , to: 'pages#password-protection'
  get "using-your-card-securely", to: 'pages#using-your-card-securely'
  get "self-employed-pensions", to: 'pages#self-employed-pensions'
  get "retire-in-portugual", to: 'pages#retire-in-portugual'
  get "money-and-mental-health", to: 'pages#money-and-mental-health'
  get "blogs-small-business" , to: 'pages#blogs-small-business'
  get "blogs-travel" , to: 'pages#blogs-travel'
  get 'blogs-personal-finance', to: 'pages#blogs-personal-finance'
end
